CREATE TYPE "public"."phases" AS ENUM('Capture stage', 'Expression of Interest', 'Tender stage');--> statement-breakpoint
CREATE TABLE "bids" (
	"id" serial PRIMARY KEY NOT NULL,
	"title" varchar(255) NOT NULL,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"deletedAt" timestamp,
	"updatedAt" timestamp,
	"deadline" timestamp,
	"phase" "phases" DEFAULT 'Capture stage',
	"author" varchar(50) NOT NULL,
	"client" serial NOT NULL,
	"country" varchar(50) NOT NULL,
	"biddingEntity" varchar(50) NOT NULL,
	"technicalUnit" varchar(50) NOT NULL,
	"consortiumRole" varchar(50) NOT NULL,
	"competence" integer NOT NULL,
	"countryExperience" integer NOT NULL,
	"clients" integer NOT NULL,
	"numberOfBidders" integer NOT NULL,
	"competitorProfile" integer NOT NULL,
	"partnerCapacity" integer NOT NULL,
	"clientPreference" integer NOT NULL,
	"clientIntelligence" integer NOT NULL,
	"clientProcurement" integer NOT NULL,
	"availabilityOfResources" integer NOT NULL,
	"contractValue" integer NOT NULL,
	"expertLoe" integer NOT NULL,
	"projectDuration" integer NOT NULL,
	"bdInput" integer NOT NULL,
	"historicalNetMargin" integer NOT NULL,
	"futureRevenue" integer NOT NULL,
	"scopeOfWork" integer NOT NULL,
	"easeOfDoingBusiness" integer NOT NULL,
	"security" integer NOT NULL,
	"reputationalRisk" integer NOT NULL,
	"goCapture" boolean NOT NULL,
	"goEoi" boolean NOT NULL,
	"goTender" boolean NOT NULL,
	"tentCapture" boolean NOT NULL,
	"tentEoi" boolean NOT NULL,
	"tentTender" boolean NOT NULL,
	"urgent" boolean NOT NULL,
	"budget" numeric NOT NULL,
	"duration" numeric NOT NULL,
	"bidDirectorCapture" numeric NOT NULL,
	"bidDirectorEoi" numeric NOT NULL,
	"bidDirectorTender" numeric NOT NULL,
	"bidManagerCapture" numeric NOT NULL,
	"bidManagerEoi" numeric NOT NULL,
	"bidManagerTender" numeric NOT NULL,
	"technicalLeadCapture" numeric NOT NULL,
	"technicalLeadEoi" numeric NOT NULL,
	"technicalLeadTender" numeric NOT NULL,
	"recLeadCapture" numeric NOT NULL,
	"recLeadEoi" numeric NOT NULL,
	"recLeadTender" numeric NOT NULL,
	"proposalWriteCapture" numeric NOT NULL,
	"proposalWriteEoi" numeric NOT NULL,
	"proposalWriteTender" numeric NOT NULL,
	"analystCapture" numeric NOT NULL,
	"analystEoi" numeric NOT NULL,
	"analystTender" numeric NOT NULL,
	"reviewerCapture" numeric NOT NULL,
	"reviewerEoi" numeric NOT NULL,
	"reviewerTender" numeric NOT NULL,
	"copyWriterCapture" numeric NOT NULL,
	"copyWriterEoi" numeric NOT NULL,
	"copyWriterTender" numeric NOT NULL,
	"recruiterAdminCapture" numeric NOT NULL,
	"recruiterAdminEoi" numeric NOT NULL,
	"recruiterAdminTender" numeric NOT NULL,
	"commLeadCapture" numeric NOT NULL,
	"commLeadEoi" numeric NOT NULL,
	"commLeadTender" numeric NOT NULL,
	"pmCapture" numeric NOT NULL,
	"pmEoi" numeric NOT NULL,
	"pmTender" numeric NOT NULL,
	"graphicDesCapture" numeric NOT NULL,
	"graphicDesEoi" numeric NOT NULL,
	"graphicDesTender" numeric NOT NULL,
	"translatorCapture" numeric NOT NULL,
	"translatorEoi" numeric NOT NULL,
	"translatorTender" numeric NOT NULL
);
--> statement-breakpoint
CREATE TABLE "clients" (
	"id" serial PRIMARY KEY NOT NULL,
	"title" varchar(255) NOT NULL,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"deletedAt" timestamp,
	"updatedAt" timestamp
);
--> statement-breakpoint
ALTER TABLE "bids" ADD CONSTRAINT "bids_client_clients_id_fk" FOREIGN KEY ("client") REFERENCES "public"."clients"("id") ON DELETE no action ON UPDATE no action;